# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: BIO
    url: /
    weight: 10
    submenu:
      - name: About Me
        url: /#about-me
      - name: Slider
        url: /#slider
      - name: Experience
        url: /#experience
      - name: Ongoing Projects
        url: /#ongoing-projects
      - name: Completed Projects
        url: /#completed-projects
  - name: Studying
    url: /#studying
    weight: 15
  - name: Experience
    url: experience/
    weight: 20
    submenu:
      - name: Experience
        url: /#experience
      - name: Hobby
        url: /#hobby
  - name: Projects
    url: projects/
    weight: 30
    submenu:
      - name: Ongoing Projects
        url: /#ongoing-projects
      - name: Completed Projects
        url: /#completed-projects
  - name: Contact
    url: contact/
    weight: 40

