# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: BIO
    url: /
    weight: 100
  - parent: BIO
    name: About Me
    url: /#about-me
    weight: 110
  - parent: BIO
    name: Experience
    url: Experience/
    weight: 120
  - parent: BIO
    name: Ongoing Projects
    url: ongoing-projects/
    weight: 130
  - parent: BIO
    name: Completed Projects
    url: completed-projects/
    weight: 140
  
  - name: Studying
    url: studying/
    weight: 200

  - name: Experience
    url: experience/
    weight: 300
  - parent: Experience
    name: Computer
    url: computer/
    weight: 310
  - parent: Experience
    name: Hobby
    url: hobby/
    weight: 320

  - name: Projects
    url: projects/
    weight: 400
  - parent: Projects
    name: Ongoing Projects
    url: ongoing-projects/
    weight: 410
  - parent: Projects
    name: Completed Projects
    url: completed-projects/
    weight: 420

  - name: Contact
    url: contact/
    weight: 500

