# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: BIO
    url: /
    weight: 10
  -parent: BIO
    - name: About Me
      url: /#about-me
      weight: 11
  -parent: BIO
    - name: Experience
      url: /#Experience
      weight: 12
  -parent: BIO
    - name: Ongoing Projects
      url: /#ongoing-projects
      weight: 13
  -parent: BIO
    - name: Completed Projects
      url: /#completed-projects
      weight: 14
  
  - name: Studying
    url: /#studying
    weight: 20

  - name: Experience
    url: experience/
    weight: 30
  -parent: Experience
    - name: Computer
      url: /#experience
      weight: 31
  -parent: Experience
    - name: Hobby
      url: /#hobby
      weight: 32

  - name: Projects
    url: projects/
    weight: 40
  -parent: Projects
    - name: Ongoing Projects
      url: /#ongoing-projects
      weight: 41
  -parent: Projects
    - name: Completed Projects
      url: /#completed-projects
      weight: 42

  - name: Contact
    url: contact/
    weight: 50

